apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgres-chart.fullname" . }}
  labels:
    app: {{ template "postgres-chart.name" . }}
    chart: {{ template "postgres-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port}}
      protocol: TCP
      name: postgres
  selector:
    app: {{ template "postgres-chart.name" . }}
    release: {{ .Release.Name }}
